spring:
  application:
    name: patient-service
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximum-pool-size: "10"
      connection-timeout: "30000"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: create-drop
server:
  port: ${PORT}
logging:
  level:
    root: INFO
    org:
      hibernate: DEBUG
      springframework: DEBUG
